# -*- coding: utf-8 -*-
"""bebida favorita

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i3wLiWQ35rBtbUasQ_Gqplw_EjiwqoYd
"""

#Algoritmo minha bebida favorita

#Entrada de valores das variáveis
bebida = str(input("Qual a sua bebida favorita? "))
valor = float(input("Qual o valor da bebida? "))
alcoolica = bool(input("É alcoolica ou não? "))

#Processamento e Saída
if (bool(alcoolica) == True):
  print("A minha bebida favorita é ", bebida, " e o valor dela é ",valor," ela é alcoolica.")
else:
  print("A minha bebida favorita é ", bebida, " e o valor dela é ",valor," ela não é alcoolica.")

almoco        = input("Almoço favorito? ")
bebida_vlr    = float(input("Preço da bebida? "))
preco_almoco  = float(input("Preço do almoço? "))
orcamento     = float(input("Qual o seu orçamento? "))
grupo         = int(input("Quantas pessoas no grupo? "))

total_almoco  = (preco_almoco+bebida)*grupo


print("Total do almoço",total_almoco)

