# -*- coding: utf-8 -*-
"""calcula desconto

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TbPxfKsq-vGNayafQvBFVmvBwt0gC_GY
"""

valorProduto = float(input("Valor Produto: "))
percentualDesconto = float(input("Percentual de desconto: "))

valorDesconto = valorProduto - ((valorProduto * percentualDesconto)/100)
print("Valor do Produto com o Desconto: ", valorDesconto)