# -*- coding: utf-8 -*-
"""Exercicios aleatórios

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SC-Thy7ozmL06s_TaX1dO1lPmpICknKb
"""

def multiplicacao(num1,num2):
  resultado = num1 * num2
  return resultado

print("Tabuada do 9: ")
for i in range(11):
 print("9 x",i, "=",multiplicacao(9,i))

estoquedeprodutos = ["smartphone", "tablet convencional", "Ipad", "Pc Gamer"]
for i in range(len(estoquedeprodutos)):
  print(i, estoquedeprodutos[i])

alteraritem = input("\n Deseja alterar algum produto? Digite Sim ou Não ")
if alteraritem == "Sim":
  alterarprod = int(input("\nDigite o código do produto que deseja alterar: "))

  novoitem = (input("\nDigite o nome do novo produto: "))
  estoquedeprodutos[alterarprod] = novoitem

  for i in range(len(estoquedeprodutos)):
    print(i, estoquedeprodutos[i])

incluiritem = input("\nDeseja incluir algum produto? Digite Sim ou Não ")
if incluiritem == "Sim":
  incluirproduto = input("\nQual produto você deseja incluir? ")
  estoquedeprodutos.append(incluirproduto)

  for i in range(len(estoquedeprodutos)):
    print(i, estoquedeprodutos[i])

'''
Faça uma função calculadora que os números e as operações serão 
feitas pelo usuário. O código deve ficar rodando infinitamente até 
que o usuário escolha a opção de sair. 
No início, o programa mostrará a seguinte lista de operações:
1: Soma
2: Subtração
3: Multiplicação
4: Divisão
0: Sair
Digite o número para a operação correspondente e caso o usuário introduza 
qualquer outro, o sistema deve mostrar a mensagem “Essa opção não existe” 
e voltar ao menu de opções.
Após a seleção, o sistema deve pedir para o usuário inserir o primeiro
 e segundo valor, um de cada. Depois precisa executar a operação e mostrar
  o resultado na tela. Quando o usuário escolher a opção “Sair”, 
  o sistema irá parar.
É necessário que o sistema mostre as opções sempre que 
finalizar uma operação e mostrar o resultado. 
'''

def calculadora(operacao):
  while (operacao != 0):
    if operacao == 1:
      valorA = float(input("Insira o primeiro valor: "))
      valorB = float(input("Insira o segundo valor: "))
      total = valorA + valorB
      print("\no Valor da soma é: ", total, "\n")
      operacao = int(input("Qual operação? \n1: Soma \n2: Subtração \n3: Multiplicação \n4: Divisão \n0: Sair \n"))    
    elif operacao == 2:
      valorA = float(input("Insira o primeiro valor: "))
      valorB = float(input("Insira o segundo valor: "))
      total = valorA - valorB
      print("O valor da subtração é: ", total, "\n")
      operacao = int(input("Qual operação? \n1: Soma \n2: Subtração \n3: Multiplicação \n4: Divisão \n0: Sair \n"))
    elif operacao == 3:
      valorA = float(input("Insira o primeiro valor: "))
      valorB = float(input("Insira o segundo valor: "))
      total = valorA * valorB
      print("O valor da multiplicação é: ", total, "\n")
      operacao = int(input("Qual operação? \n1: Soma \n2: Subtração \n3: Multiplicação \n4: Divisão \n0: Sair \n"))
    elif operacao == 4:
      valorA = float(input("Insira o primeiro valor: "))
      valorB = float(input("Insira o segundo valor: "))
      total = valorA / valorB
      print("O valor da divisão é: ", total, "\n")
      operacao = int(input("Qual operação? \n1: Soma \n2: Subtração \n3: Multiplicação \n4: Divisão \n0: Sair \n"))
    else:
      print("\nOpção não disponível \n")
      operacao = int(input("Qual operação? \n1: Soma \n2: Subtração \n3: Multiplicação \n4: Divisão \n0: Sair \n"))

  print ("Aplicativo encerrado")

print("Bem vindo a calculadora")
operacao = int(input("Qual operação você deseja? \n1: Soma \n2: Subtração \n3: Multiplicação \n4: Divisão \n0: Sair \n"))
total = 0.0

calculadora(operacao)

# Faça um programa que peça uma nota, entre zero e dez. 
# Mostre uma mensagem caso o valor seja inválido e continue pedindo
# até que o usuário informe um valor válido. 


valor = int(input("Insira uma nota de 0 à 10. "))

while valor < 0 or valor > 10:
  print("Valor errado, digite uma nota de 0 a 10. ")
  valor = int(input("Insira uma nota de 0 à 10. "))
else:
  print("Nota inserida, ", valor)

# Hoje é segunda feira precisamos regar todas as plantas
# imprime uma mensagem por cada planta pedindo ao robo 
# para rega-la
'''
for i in range(6):
  planta_atual = str(i)
  if planta_atual == "0":
    nome_planta = "Tomate 0"
  elif planta_atual == "1":
    nome_planta = "Batata 1"
  elif planta_atual == "2":
    nome_planta = "Cenoura 2"
  elif planta_atual == "3":
    nome_planta = "Tomate 3"
  elif planta_atual == "4":
    nome_planta = "Batata 4"
  elif planta_atual == "5":
    nome_planta = "Cenoura 5"
  print("Regar a planta número: " + planta_atual)

'''
conta_planta = 0
while (conta_planta <= 5):
  planta_atual = str(conta_planta)
  if planta_atual == "0":
    nome_planta = "Tomate 0"
  elif planta_atual == "1":
    nome_planta = "Batata 1"
  elif planta_atual == "2":
    nome_planta = "Cenoura 2"
  elif planta_atual == "3":
    nome_planta = "Tomate 3"
  elif planta_atual == "4":
    nome_planta = "Batata 4"
  elif planta_atual == "5":
    nome_planta = "Cenoura 5"
  
  print("Regar a planta: " + nome_planta)
  conta_planta += 1

vetor = [];
fim = True
contador = 0

while fim == True:
  texto = input("Insira um texto: ")
  vetor.append(texto)
  contador += 1
  try:
    termina = int(input("Vai inserir mais algum texto. Se sim digite 1, senão 2, para finalizar: "))
    if (termina == 2):
      print(vetor[contador])
      fim = False
    else:
      print(vetor)
  except:
    print("Informação errada, informe 1 para SIM ou 2 para NÃO")

# Faça um programa que leia um nome de usuário e a sua senha 
# e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro
# e voltando a pedir as informações.

import getpass

def verifica_pass(usuario, senha):
  ret = False
  while usuario == senha:
    print("A senha não pode ser igual ao nome de usuário.\nDigite uma nova senha: ")
    senha = getpass.getpass("Insira a senha: ")
  else:
    return(print("Nova senha incluida com sucesso. "))  

usuario = input("Insira o nome de usuário: ")
senha = getpass.getpass("Insira a senha: ")

verifica_pass(usuario,senha)

# Faça um programa que leia e valide as seguintes informações:
# Nome: maior que 3 caracteres;
# Idade: entre 0 e 150;
# Salário: maior que zero;
# Sexo: 'f' ou 'm';
# Estado Civil: 's', 'c', 'v', 'd';

def validainf(nome,idade,salario,sexo,estado_civil):

  while len(nome)<=3 or idade > 150 or idade < 0 or salario <= 0 or sexo not in(1,2) or estado_civil not in(1,2,3,4):
    if(len(nome)<=3):
      return(print("ERRO: Nome menor que 3 caracteres"))
    elif(idade > 150 or idade < 0):
      return(print("ERRO: idade precisa ser entre 0 e 150"))
    elif(salario < 0):
      return(print("ERRO: salário precisa ser maior que zero"))
    elif(sexo not in(1,2)):
      return(print("ERRO: sexo precisa ser masculino ou feminino"))
    elif(estado_civil not in(1,2,3,4)):
      return(print("ERRO: Estado Civil precisa ser \n1.Solteiro(a) \n2.Casado(a) \n3.Viúvo(a) \n4.Divorciado(a) "))  
    else:    
      return(print("Validação deu erro"))
      
  else:
    #Descricao estado civil
    if(estado_civil == 1):
      estcivil_desc = "Solteiro(a)"
    elif(estado_civil == 2):
      estcivil_desc = "Casado(a) "
    elif(estado_civil == 3):
      estcivil_desc = "Viúvo(a)"
    elif(estado_civil == 4):
      estcivil_desc = "Divorciado(a)"  
    #Descricao Sexo  
    if(sexo == 1):
      sexo_desc = "Masculino"
    else:
      sexo_desc = "Feminino"
    return(print("Nome:", nome,"\nIdade",idade,"\nSalário:",salario,"\nSexo:",sexo_desc,"\nEstado Civil:",estcivil_desc))

# Declaração das Variáveis
nome    = input("Qual é o Nome? ")
idade   = int(input("Qual é a idade? "))
salario = float(input("Qual o salário? "))
sexo    = int(input("Qual o sexo? \n1.Masculino \n2.Feminino \n"))
estado_civil = int(input("Qual o estado civil? \n1.Solteiro(a) \n2.Casado(a) \n3.Viúvo(a) \n4.Divorciado(a) \n"))

#Chamada da Função
validainf(nome,idade,salario,sexo,estado_civil)

# Supondo que a população de um país A seja da ordem de 80000 habitantes 
# com uma taxa anual de crescimento de 3% e que a população de B 
# seja 200000 habitantes com uma taxa de crescimento de 1.5%. 
# Faça um programa que calcule e escreva o número de anos necessários 
# para que a população do país A ultrapasse ou iguale a população do país B, 
# mantidas as taxas de crescimento.


def calcula_taxa_cresc(cresc_paisA,cresc_paisB,ano):
  while cresc_paisA <= cresc_paisB:
    cresc_paisA += cresc_paisA * 0.03
    cresc_paisB += cresc_paisB * 0.015
    ano = ano + 1
  else:
    return(print("Foi necessário ", ano," anos para passar."))

cresc_paisA = float(input("Digite quantos habitantes, país A: "))
cresc_paisB = float(input("Digite quantos habitantes, país B: "))
ano = 0

calcula_taxa_cresc(cresc_paisA,cresc_paisB,ano)

