# -*- coding: utf-8 -*-
"""Exercicio array

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1af4mCINUdIzF6yEN7CtFqA0UA1ELOkPI
"""

listadecompras = ["banana", "café", "pão", "açúcar", "arroz", "leite", "requeijão", "azeitona", "cuscuz", "tofú", "panetone", "feijão", "cerveja", "chocolate"]
doce = str(input("Digite o elemento: "))

def acharelemento (array, elemento):
  encontramos = False
  
  for i in range(len(array)):
    if elemento == array[i]:
      encontramos = True
      break
  

  if (encontramos == True):
    print("Encontramos o elemento", elemento, "no índice: ", i)
  
  else:
    print("Não encontramos o elemento '-' ")



acharelemento(listadecompras, doce)

listadecompras = ["banana", "café", "pão", "açúcar", "arroz", "leite", "requeijão", "azeitona", "cuscuz", "tofú", "panetone", "feijão", "cerveja", "chocolate"]


def acharelemento (array):
  encontramos = False
  doce = str(input("Digite o elemento: "))

  for i in range(len(array)):
    if doce == array[i]:
      encontramos = True
      break

  if (encontramos == True):
    print("Encontramos o elemento", doce, "no índice: ", i)
  
  else:
    print("Não encontramos o elemento '-' ")
    acharelemento(listadecompras)


acharelemento(listadecompras)