# -*- coding: utf-8 -*-
"""Exercicio Numeros

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SDY1wOEimcvUOlUefmDC_XKHBW1Fodar

Atividade para entregar na próxima terça-feira:

1) Replicar a função feita na última aula, onde pedíamos para o usuário inserir um número menor que 100. Inserindo mensagens caso o usuário não digitar o esperado. E pedir para ele digitar um número novamente até que seja digitado um número válido.

2) Adicionar a verificação de caso o usuário digitar zero, avisa-lo que “0” não é um número válido.

3) Criar uma outra função com as mesmas funcionalidades que a primeira, porém o número precisa ser menor que 100 e par.

4) Criar outra função com as mesmas funcionalidades da primeira, porém o número precisa ser menor que 100 e divisível por 2 e 3.


Mandem as atividades feitas no canal de atividades feitas!
Bom final de semana galera 🧡
"""

# Exercício que compõem 1 e 2

def validaNumeros():
  num_validado = False

  while (num_validado == False):
    try:
      numero = int(input("Informe um numero menor que 100: \n"))
      if (numero >= 100):
        print("Número informado é maior que 100.")
      elif (numero == 0):
        print("'0' não é um número válido")
      else:
        print("Número informado corretamente é: ", numero)
        num_validado = True
    except:
      print("necessário informar um numero inteiro.")

validaNumeros()

# Exercício que compõem 3
def validaNumeros():
  num_validado = False

  while (num_validado == False):
    try:
      numero = int(input("Informe um numero menor que 100 e que seja par: \n"))
      if (numero >= 100):
        print("Número informado é maior que 100.")
      elif (numero %2 != 0):
        print("Número informado é ímpar, informe um número par ")
      elif (numero == 0):
        print("'0' não é um número válido")
      else:
        print("Número informado corretamente é: ", numero)
        num_validado = True
    except:
      print("necessário informar um numero inteiro.")

validaNumeros()

# Exercício 4
def validaNumeros():
  num_validado = False

  while (num_validado == False):
    try:
      numero = int(input("Informe um numero menor que 100 e divisivel por 2 e 3: \n"))
      if (numero >= 100):
        print("Número informado é maior que 100.")
      elif (numero == 0):
        print("'0' não é um número válido")
      elif (numero %2 != 0 and numero %3 != 0):
        print("Digite um numero divisivel por 2 e 3 ")
      else:
          print("Número informado corretamente é: ", numero)
          num_validado = True
    except:
      print("necessário informar um numero inteiro.")

validaNumeros()

