# -*- coding: utf-8 -*-
"""Nro Andares

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DcCcST_OvbKMfS7L2krIbyDfDHYZD2zn
"""

nro_andares = int(input("Informe quantos andares: "))
andar_exilado = int(input("Qual andar deseja evitar? "))
contador = nro_andares

# REPITA
while True:
  print("andar nro: ",contador)
  contador = contador - 1
  if contador == andar_exilado: 
    contador = contador - 1    
  elif contador == 0:
    break

# PARA

nro_andares = int(input("Informe quantos andares: "))
andar_exilado = int(input("Qual andar deseja evitar? "))

for contador in range((nro_andares), 0, -1):
  if contador == andar_exilado:
    contador = contador - 1
  else:
    print("andar ",contador)
    contador = contador - 1

# ENQUANTO

nro_andares = int(input("Informe quantos andares: "))
andar_exilado = int(input("Qual andar deseja evitar? "))
contador = nro_andares

while (contador != 0):
  if contador == andar_exilado:
    contador = contador - 1
  else:
    print("Andar nro: ", contador)
    contador = contador - 1