# -*- coding: utf-8 -*-
"""Regue a planta

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zI9oS0vdSCZHzZ-WYD0XWsZZAkOcNrCV
"""

# Hoje é segunda feira precisamos regar todas as plantas
# imprime uma mensagem por cada planta pedindo ao robo 
# para rega-la

conta_planta = 0
while (conta_planta <= 5):
  planta_atual = str(conta_planta)
  if planta_atual == "0":
    nome_planta = "Tomate 0"
  elif planta_atual == "1":
    nome_planta = "Batata 1"
  elif planta_atual == "2":
    nome_planta = "Cenoura 2"
  elif planta_atual == "3":
    nome_planta = "Tomate 3"
  elif planta_atual == "4":
    nome_planta = "Batata 4"
  elif planta_atual == "5":
    nome_planta = "Cenoura 5"
  
  print("Regar a planta: " + nome_planta)
  conta_planta += 1

# Regar somente os pares

for i in range(0,6,+2):
  planta = i
  print("Regue a planta", planta)

# Regar as batatas agora elas estão em outra ordem
# 0-tomate, 1-tomate, 2-tomate, 3-batata, 4-batata, 5-batata

for i in range(6):
  if i not in (0,1,2):
    planta = i
    print("Regue a planta", planta)

# Regar somente o tomate agora elas estão em outra ordem
# 0-tomate, 1-tomate, 2-batata, 3-batata, 4-tomate, 5-tomate

for i in range(6):
  if i not in (2,3):
    planta = i
    print("Regue a planta", planta)

# Regar todas mas agora de trás para frente
# 0-tomate, 1-batata, 2-cenoura, 3-tomate, 4-batata, 5-cenoura

for i in range(5,-1,-1):
  #if i not in (2,3):
  planta = i
  print("Regue a planta", planta)