# -*- coding: utf-8 -*-
"""Sistema Moderno

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14bp-5VO5lKawJ4G_8ZpmYja2CWF0mcIr
"""

lista_produto = []

def telaprincipal(lista_produto):
  try:
    menuSistema = int(input("Bem vindo ao Sistema Moderno Menu: \n 1. Novo Produto \n 2. Mostrar produtos \n 3. Alterar produtos \n 4. Excluir produtos \n 5. Encerrar \n"))   
    if (menuSistema == 1):
      incluiNovoProduto(lista_produto)
    elif (menuSistema == 2):
      mostraLista(lista_produto)
    elif (menuSistema == 3):
      alterarProduto(lista_produto)
    elif (menuSistema == 4):
      excluirProduto(lista_produto)
    elif (menuSistema == 5):
      print("\n Opção digitada:",menuSistema,"- Até breve !!!")
    else:
      print("\n Opção inválida!")
  except:
    print("Valor digitado inválido, insira um número.")
    print("\n")
    telaprincipal(lista_produto)

def incluiNovoProduto(lista):
  try:
    novo_produto = str(input("\n Insira um novo produto: "))
    lista_produto.append(novo_produto)
    print("\n")
    telaprincipal(lista_produto)
  except:
    print("Valor digitado inválido, insira um texto.")
    print("\n")
    telaprincipal(lista_produto)

def excluirProduto(lista):
  try:
    print("\n Lista de produtos no estoque: ")
    for i in range(len(lista_produto)):      
      print(i,"-",lista_produto[i])

    del_produto = int(input("\n Insira o numero do produto que deseja retirar da lista acima: "))
    lista_produto.pop(del_produto)
  except:
    print("Valor digitado inválido, insira um numero.")
    print("\n")
    telaprincipal(lista_produto)

  telaprincipal(lista_produto)

def alterarProduto(lista):
  try:
    print("\n [ALTERAR] - Lista de produtos: ")
    for i in range(len(lista_produto)):      
      print(i,"-",lista_produto[i])

    alt_produto = int(input("\n Insira o numero do produto que deseja alterar da lista acima: "))
    lista_produto[alt_produto] = str(input("\n Digite o nome do novo produto: "))
  except:
    print("Valor digitado inválido, insira um numero.")
    print("\n")
    telaprincipal(lista_produto)

  telaprincipal(lista_produto)

def mostraLista(lista):
  contador = 1
  if (len(lista_produto) > 0):
    print("\n Lista de produtos no estoque: ")
    for i in range(len(lista_produto)):      
      print(lista_produto[i])
  else:
    print("\n Insira um produto na lista para listarmos ele por aqui.")
  
  print("\n")
  telaprincipal(lista_produto)

telaprincipal(lista_produto)

