# -*- coding: utf-8 -*-
"""Tabuada

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YJ888RASapcH9F8hedJ4b5T2zCWN48n2
"""

def multiplicacao(num1,num2):
  resultado = num1 * num2
  return resultado

print("Tabuada do 9: ")
for i in range(11):
 print("9 x",i, "=",multiplicacao(9,i))

def multiplicacao(num1,num2):
  resultado = num1 * num2
  return resultado

print("Tabuada")
try:
  nro_tabuada = int(input("Informe de qual a tabuada que você quer ver: "))
  for i in range(11):
    print(str(nro_tabuada),"x",i, "=",multiplicacao(nro_tabuada,i))
except:
  print("Informe somente numeros de 1 a 9, letras ou sinais não permitidos.")