# -*- coding: utf-8 -*-
"""While - Try - Except - If - Function

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BPJ6WNiHYXlpx6Hw1pG3Xxv9sPt4SdHP
"""

#num % 2 (o resultado = 0 então é par)
def mostrarNumero():
  numeroValido = False

  while(numeroValido == False):
    try:
      num = int(input("Digite um numero menor que 100 e par: "))
      if (num > 100 or num % 2 != 0): 
        print("Numero não pode ser maior que 100 e p")        
        #mostrarNumero()
      else:
        print("Numero digitado: ", num)
        numeroValido = True
    except:
      print("É necessário digitar um numero inteiro")
      #mostrarNumero()

mostrarNumero()

